#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="2.4.54"
URL="https://github.com/devcode-it/openstamanager/releases/download/v$VERSION/openstamanager-$VERSION.zip"

dl $URL /usr/local/src
