#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION=$(gh_releases devcode-it/openstamanager | grep -vi 'beta' | sort -V | tail -1)
URL="https://github.com/devcode-it/openstamanager/releases/download/$VERSION/OpenSTAManager-$VERSION.zip"

dl $URL /usr/local/src
