#!/bin/bash -e
# regenerate OpenSTAManager secrets

. /etc/default/inithooks

SALT=$(mcookie | cut -c1-16)
PASSWORD=$(mcookie)
CONF=/var/www/openstamanager/data/config-internal.php

updateconf() {
    sed -i "s|$1.*|$1 => '$2',|;" $CONF
}

# Note the trailing single quote is important!
updateconf "passwordSalt'" $SALT
updateconf "password'" $PASSWORD
updateconf "cryptKey'" $(mcookie)
updateconf "hashSecretKey'" $(mcookie)

$INITHOOKS_PATH/bin/mysqlconf.py --user openstamanager --pass="$PASSWORD"
